apps/two/urls.py
from django.conf.urls import url
from . import views           
urlpatterns = [
  url(r'^dashboard', views.dashboard, name = 'dashboard'),
  url(r'^create$', views.create, name = 'create'),
  url(r'^share/(?P<quote_id>\d+)$', views.share , name="share"),
  url(r'^remove/(?P<quote_id>\d+)$', views.remove , name="remove"),
  url(r'^logout$', views.logout , name="logout"),
  url(r'^summary/(?P<poster_id>\d+)$', views.summary, name ="summary"),
   url(r'^count$', views.count, name = 'count')
]

apps/users/urls.py
from django.conf.urls import url
from . import views           
urlpatterns = [
  url(r'^$', views.index, name = 'index'),
  url(r'^register$', views.register, name = 'register'),
  url(r'^login$', views.login, name = 'login')
]

test3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include ('apps.users.urls', namespace = 'users')),
    url(r'^two/', include ('apps.two.urls', namespace = 'two')),
]

apps/two/models.py
from __future__ import unicode_literals

from django.db import models

from ..users.models import User 
import datetime
import re


class CiteManager(models.Manager):

    def citation(self, postData, user_id):
        errors = []
        if len(postData['author']) < 3:
            errors.append("'Quoted by:' should have more than 3 characters") 

        if len(postData['quote']) < 11:
            errors.append("'Quote' should have more than 10 characters") 
        
        print len(errors)

        if len (errors) > 0:
            return (False, errors)
        else:
            newposter = User.objects.get(id=user_id)
            newquote = Cite.objects.create(
            author = postData ['author'],
            quote = postData['quote'],
            poster = newposter
        )
        newquote.shared_with.add(newposter)
        newquote.save()

        return (True, "success")

    def join(self, user_id, quote_id):
        person = User.objects.get(id=user_id)
        instance = Cite.objects.get(id=quote_id)
        instance.shared_with.add(person)
        instance.save()

    def leave(self, user_id, quote_id):
        person = User.objects.get(id=user_id)
        instance= Cite.objects.get(id=quote_id)
        instance.shared_with.remove(person)
        instance.save()



class Cite(models.Model):
    quote = models.TextField()
    author = models.CharField(max_length = 50)
    poster = models.ForeignKey(User, related_name = 'post_person')
    shared_with = models.ManyToManyField(User, related_name='shared')
    objects = CiteManager()

apps/users/models.py
from __future__ import unicode_literals
from django.db import models
import re
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
import bcrypt
import datetime
import re


hash1 = bcrypt.hashpw('password'.encode(), bcrypt.gensalt())


class UserManager(models.Manager):
    
    def validate(self, postData):
        errors = {}
        EMAIL_REGEX = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
        NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')
        hash1 = bcrypt.hashpw('password'.encode(), bcrypt.gensalt())
        print hash1
    
        if len(postData['name']) < 3 or len(postData['username']) < 3:
            errors['name_errors'] = "Name and username should be at least 3 characters"

        if not re.match(NAME_REGEX, postData['name']): 
            errors["name"] = "Name takes only characters"

        if not re.match(NAME_REGEX, postData['username']):
            errors["username"] = "Username takes only characters"
        
        if len(postData['password']) < 8:
            errors['password']="Password needs to have 8 characters or more. "
        
        if postData['password'] != postData['confirm_password']:
            errors["password"] = "Password and confirm password must match"
            
        print len(errors)

        if len(errors) > 0:
            return (False, errors)
        else:
            hash1 = bcrypt.hashpw(postData["password"].encode(), bcrypt.gensalt(5))
            user = User.objects.create(
                name = postData ['name'],
                username = postData ['username'],
                email = postData ['email'],
                date_of_birth = postData ['dob'],
                password = hash1
            )
            return (True, user)

    def login(self, postData):
        errors = {}

        if len(self.filter(username=postData['username'])) > 0:
            user = self.filter(username=postData['username'])[0]
            if not bcrypt.checkpw(postData['password'].encode(), user.password.encode()):
                errors ['password'] = "password"
                return False
            else:
                return (True, user)
        else:
            errors ['username'] = "Wrong username"
            return False
    

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    date_of_birth = models.DateField(null=True)
    objects = UserManager()

apps/two/views.py
from django.shortcuts import render, redirect , HttpResponse
from . models import *
from django.contrib import messages
from ..users.models import User

def dashboard(request):
    post_person = User.objects.get(id=request.session['user_id'])
    context = {
        'my_quotes' : Cite.objects.filter(shared_with=post_person),
        'other_quotes' : Cite.objects.exclude(shared_with=post_person)
    }
    return render (request, 'two/dashboard.html', context)
    

def create(request):
    if "user_id" not in request.session:
        return redirect("/")
    result = Cite.objects.citation(request.POST, request.session['user_id'])

    if result [0]:
        return redirect ('two:dashboard')
    else: 
        for error in result[1]:
            messages.error(request,error)
        return redirect ('two:dashboard')

def share(request, quote_id):
    if "user_id" not in request.session:
        return redirect("/")
    Cite.objects.join(request.session['user_id'], quote_id)
    return redirect ('two:dashboard')

def summary(request, poster_id):
    if "user_id" not in request.session:
        return redirect("/")
    context = {
        'posts': Cite.objects.get(id=poster_id)
    }
    return render(request, 'two/summary.html', context)

def remove (request, quote_id):
    if "user_id" not in request.session:
        return redirect("/")
    Cite.objects.leave(request.session['user_id'], quote_id)
    return redirect ('two:dashboard')

def logout(request):
    request.session.clear()
    return redirect('/')

def count(request, poster_id):
    count = Cite.objects.filter(id=poster_id).count()
    context = {
        'count': count
    }
    return render(request, 'two/summary.html', context)

apps/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages

from django.core.urlresolvers import reverse

from models import User

def index(request):
    return render(request, "users/index.html")

def register(request):
    result = User.objects.validate(request.POST)
    
    if result[0]:
        request.session['username'] = request.POST['username']
        request.session['user_id'] = result[1].id
        return redirect('two:dashboard')
    else:
        for tag, error in result[1].iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')

def login(request):
    print request.POST
    result = User.objects.login(request.POST)

    if result == False:
        messages.error(request, "wrong password!")
        return redirect('/')
    else:
        request.session['username'] = request.POST['username']
        request.session['user_id'] = result[1].id
        return redirect('two:dashboard')

apps/two/templates/two/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'two/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
    <title>Document</title>
</head>
<body>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    
    <div>
		<a href="{% url 'two:logout' %}">Logout</a>
	</div>

    <h1>Welcome, {{request.session.username}}</h1>

    <div class=quotables>
            <h2>Quotable Quotes:</h2>
            <table border ="1">
                <thead>
                    <tr>
                       <th></th>
                    </tr>
                </thead>    
                <tbody>
                    {% for quote in other_quotes %}
                    <div>
                        <tr>
                        <!-- <td><a href="/two/summary/{{item.id}}">{{item.item}}</a></td> -->
                            <td>{{quote.author}}:{{quote.quote}} <br>
                                <a href="/two/share/{{quote.id}}">Add to my Wishlist</a><br>
                            <p>Posted By <a href="/two/summary/{{quote.poster_id}}">{{quote.poster.username}}</a></p>
                            </td>
                        </tr>
                    </div> 
                </tbody>
                    {% endfor %}
            </table>
        </div>

    <div class=favorites>
        <h2>Your Favorites:</h2>
        <table border ="1">
            <thead>
                <tr>
                    <th></th>
                </tr>
            </thead>    
            <tbody>
                {% for quote in my_quotes %}
                <div>
                    <tr>
                    <!-- <td><a href="/two/summary/{{item.id}}">{{item.item}}</a></td> -->
                        <td>{{quote.author}}:{{quote.quote}} <br>
                        <a href="/two/remove/{{quote.id}}">Remove from my My List</a>
                        <p>Posted By <a href="/two/summary/{{quote.poster_id}}">{{quote.poster.username}}</a></p>
                        </td>
                    </tr>
               </div> 
            </tbody>
                {% endfor %}
        </table>
    </div>















    <div id=add>
        <h1>Contribute a Quote:</h1>
        <form action="{% url 'two:create' %}" method ='post'>
        {% csrf_token %}
            <label for="author">Quoted by:</label>
            <input type="text" name="author" id="author"><br><br>
            <label for="quote">Quote:</label>
            <textarea name="quote" id="quote" cols="50" rows="10"></textarea><br>
            <input type="submit" value="Submit">
        </form>
    </div>
















</body>
</html>

apps/two/templates/two/summary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <title>Post Summary</title>
</head>
<body>
    <div>
        <a href="{% url 'two:dashboard' %}">Dashboard</a>
        <a href="{% url 'two:logout' %}">Logout</a>
    </div>
    <div>
            
        <h1>Posts by {{posts.poster.username}}</h1> 
        <h2>Count:</h2><a href="{% url 'two:count' %}"></a>

    

        {% for post in posts.shared_with.all %}
            {{post.author}}
            {{post.quote}}
        {% endfor %}
           
    </div>
</body>
</html>

apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Registration</title>
</head>
<body>
    
    <div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <form action="{% url 'users:register' %}" id=reg_box method="post">
        {% csrf_token %}
            <fieldset id="fset">
                <legend id=legend>Register</legend>
                <label for="name">Name:</label><br><input type="text" name="name"><br>
                <label for="username">Username:</label><br><input type="text" name="username"><br>
                <label for="email">Email:</label><br><input type="text" name="email"><br>
                <label for="Password">Password:</label><br><input type="password" name="password"><br>
                <label for="cpassword">Confirm Password:</label><br><input type="password" name="confirm_password"><br>
                <label for="dob">Date of Birth:</label><br><input type="date" name="dob"><br>
                <input type="submit" value="Register" id=submit><br>
        </fieldset>
        </form>     
    </div>

    <div>
        <form action="{% url 'users:login' %}" id=login_box method="POST">
            {% csrf_token %}
            <fieldset id="fset">
                <legend id=legend>Login</legend>
                <label for="Username">Username:</label><br><input type="text" name="username"><br>
                <label for="Password">Password:</label><br><input type="password" name="password"><br>
                <input type="submit" value="Login" id=submit>
            </fieldset>
        </form>     
    </div>



</body>
</html>